module Special
  private

  class UnimplementedError < RuntimeError

  end

  public

  class PlaceHolder
    include Singleton
  end

  PH: PlaceHolder

  class Optional
    include Singleton
  end

  OPT: Optional

  UNIMPLEMENTED: UnimplementedError
end